[tool.poetry]
name = "coursework-drf"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.2.6"
psycopg2 = "^2.9.10"
pillow = "^11.3.0"
djangorestframework = "^3.16.1"
dotenv = "^0.9.9"
djangorestframework-simplejwt = "^5.5.1"
flake8 = "^7.3.0"
black = "^25.1.0"
isort = "^6.0.1"
requests = "^2.32.5"
celery = "^5.5.3"
redis = "^6.4.0"
eventlet = "^0.40.3"
django-celery-beat = "^2.8.1"
django-cors-headers = "^4.8.0"
drf-yasg = "^1.21.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
