# Generated by Django 5.2.6 on 2025-09-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_related_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите время выполнения привычки (не более 120 секунд)",
                null=True,
                verbose_name="Время выполнения полезной привычки",
            ),
        ),
    ]
