# Generated by Django 5.2.6 on 2025-09-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_execution_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="habit_time",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату, когда нужно сделать",
                null=True,
                verbose_name="Дата, когда нужно сделать",
            ),
        ),
    ]
